### PR TITLE
add startup scripts for windows and linux

### PR DESCRIPTION
**Pull request by birdy81**
these scripts take the inspectit agent and starts all services

---
This change is [Reviewable](https://reviewable.io/reviews/inspectit-labs/spring-petclinic-microservices/3)

### CODE REVIEW

**Comment by ivansenic** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[start_all_with_inspectIT.sh, line 68 at r1](https://reviewable.io:443/reviews/inspectit-labs/spring-petclinic-microservices/3#-Ki4aPzrE98VDmh8zLf2:-Ki4aPzrE98VDmh8zLf3:bka3px0) ([raw file](https://github.com/inspectit-labs/spring-petclinic-microservices/blob/2fae3a0cfea3414046f5ef6947a7c7c969714c26/start_all_with_inspectIT.sh#L68)):*
> ```Shell
> 
> else
>   	echo Agent jar not found. Specify the path to the inspectIT agent
> ```

small formatting issue here

---

*[stop_all.sh, line 1 at r1](https://reviewable.io:443/reviews/inspectit-labs/spring-petclinic-microservices/3#-Ki4aZaVO87g-clIdcvt:-Ki4aZaVO87g-clIdcvu:bsbowc9) ([raw file](https://github.com/inspectit-labs/spring-petclinic-microservices/blob/2fae3a0cfea3414046f5ef6947a7c7c969714c26/stop_all.sh#L1)):*
> ```Shell
> #!/bin/sh
> ```

we don't provide the ```stop_all.bat``` on purpose or?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/inspectit-labs/spring-petclinic-microservices/3)*

**Comment by ivansenic** [comment]
any chance to change the mod of the checked in files, as these are scripts they should be executable.. However, when I pulled them down they are not for me.. Can you quickly check?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/inspectit-labs/spring-petclinic-microservices/3#-:-Ki4cqD05-mSEl9hl42z:b-x7mi8u)*

**Comment by ivansenic** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[start_all_with_inspectIT.bat, line 76 at r1](https://reviewable.io:443/reviews/inspectit-labs/spring-petclinic-microservices/3#-Ki4fM0fOq0_Vg3OJiAH:-Ki4fM0fOq0_Vg3OJiAI:b65mfs3) ([raw file](https://github.com/inspectit-labs/spring-petclinic-microservices/blob/2fae3a0cfea3414046f5ef6947a7c7c969714c26/start_all_with_inspectIT.bat#L76)):*
> ```Batchfile
> 	if errorlevel 1 (if %x% leq 180 goto :loop3) else ( start "" http://localhost:8080 )
> 	set /a "x = 0"
> 	
> ```

can we print out some final message here, just to also log in the console as well that everything has started

---

*[start_all_with_inspectIT.sh, line 66 at r1](https://reviewable.io:443/reviews/inspectit-labs/spring-petclinic-microservices/3#-Ki4f87rswJ5h1wIqCqc:-Ki4f87rswJ5h1wIqCqd:b65mfs3) ([raw file](https://github.com/inspectit-labs/spring-petclinic-microservices/blob/2fae3a0cfea3414046f5ef6947a7c7c969714c26/start_all_with_inspectIT.sh#L66)):*
> ```Shell
> 	
> 	xdg-open http://localhost:8080
> ```

can we print out some final message here, just to also log in the console as well that everything has started

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/inspectit-labs/spring-petclinic-microservices/3)*

**Review by ivansenic — CHANGES_REQUESTED** [review]
Please check comments in Reviewable..

**Comment by birdy81** [comment]
*[stop_all.sh, line 1 at r1](https://reviewable.io:443/reviews/inspectit-labs/spring-petclinic-microservices/3#-Ki4aZaVO87g-clIdcvt:-Ki4m567e1whF9eGzf4k:bxarznl) ([raw file](https://github.com/inspectit-labs/spring-petclinic-microservices/blob/2fae3a0cfea3414046f5ef6947a7c7c969714c26/stop_all.sh#L1)):*
<details><summary><i>Previously, ivansenic (Ivan Senic) wrote…</i></summary><blockquote>

we don't provide the ```stop_all.bat``` on purpose or?
</blockquote></details>

I just created this script to easily stop all services on linux because they are all running in the background. Do you think it is not needed?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/inspectit-labs/spring-petclinic-microservices/3)*

**Comment by ivansenic** [comment]
*[stop_all.sh, line 1 at r1](https://reviewable.io:443/reviews/inspectit-labs/spring-petclinic-microservices/3#-Ki4aZaVO87g-clIdcvt:-Ki4qjt1SGDvBs0NDeIx:b-kn7le5) ([raw file](https://github.com/inspectit-labs/spring-petclinic-microservices/blob/2fae3a0cfea3414046f5ef6947a7c7c969714c26/stop_all.sh#L1)):*
<details><summary><i>Previously, birdy81 (Christian Vögele) wrote…</i></summary><blockquote>

I just created this script to easily stop all services on linux because they are all running in the background. Do you think it is not needed?
</blockquote></details>

No stop_all is great I like it, but you did not create a same script for the Windows? Any reasons why>

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/inspectit-labs/spring-petclinic-microservices/3)*

**Comment by birdy81** [comment]
i changed the mod to 755

---

Reviewed 4 of 4 files at r1.
Review status: 2 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[stop_all.sh, line 1 at r1](https://reviewable.io:443/reviews/inspectit-labs/spring-petclinic-microservices/3#-Ki4aZaVO87g-clIdcvt:-Ki53LNPUuVbqEf8f64W:b-extntr) ([raw file](https://github.com/inspectit-labs/spring-petclinic-microservices/blob/2fae3a0cfea3414046f5ef6947a7c7c969714c26/stop_all.sh#L1)):*
<details><summary><i>Previously, ivansenic (Ivan Senic) wrote…</i></summary><blockquote>

No stop_all is great I like it, but you did not create a same script for the Windows? Any reasons why>
</blockquote></details>

Wie don't need one for windows ;-)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/inspectit-labs/spring-petclinic-microservices/3#-:-Ki53SM3iQadyOeX2Pxt:b-7jnwyh)*

**Comment by birdy81** [comment]
Review status: 2 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[start_all_with_inspectIT.bat, line 76 at r1](https://reviewable.io:443/reviews/inspectit-labs/spring-petclinic-microservices/3#-Ki4fM0fOq0_Vg3OJiAH:-Ki53bp7_uvoWHC2zgKP:b-896fix) ([raw file](https://github.com/inspectit-labs/spring-petclinic-microservices/blob/2fae3a0cfea3414046f5ef6947a7c7c969714c26/start_all_with_inspectIT.bat#L76)):*
<details><summary><i>Previously, ivansenic (Ivan Senic) wrote…</i></summary><blockquote>

can we print out some final message here, just to also log in the console as well that everything has started
</blockquote></details>

Done.

---

*[start_all_with_inspectIT.sh, line 66 at r1](https://reviewable.io:443/reviews/inspectit-labs/spring-petclinic-microservices/3#-Ki4f87rswJ5h1wIqCqc:-Ki53d9zRGtm_jK-mpU4:b-896fix) ([raw file](https://github.com/inspectit-labs/spring-petclinic-microservices/blob/2fae3a0cfea3414046f5ef6947a7c7c969714c26/start_all_with_inspectIT.sh#L66)):*
<details><summary><i>Previously, ivansenic (Ivan Senic) wrote…</i></summary><blockquote>

can we print out some final message here, just to also log in the console as well that everything has started
</blockquote></details>

Done.

---

*[start_all_with_inspectIT.sh, line 68 at r1](https://reviewable.io:443/reviews/inspectit-labs/spring-petclinic-microservices/3#-Ki4aPzrE98VDmh8zLf2:-Ki53dfYIa9-UThztWBe:b-896fix) ([raw file](https://github.com/inspectit-labs/spring-petclinic-microservices/blob/2fae3a0cfea3414046f5ef6947a7c7c969714c26/start_all_with_inspectIT.sh#L68)):*
<details><summary><i>Previously, ivansenic (Ivan Senic) wrote…</i></summary><blockquote>

small formatting issue here
</blockquote></details>

Done.

---

*[stop_all.sh, line 1 at r1](https://reviewable.io:443/reviews/inspectit-labs/spring-petclinic-microservices/3#-Ki4aZaVO87g-clIdcvt:-Ki53eBwejEjBKqzhZcm:b-896fix) ([raw file](https://github.com/inspectit-labs/spring-petclinic-microservices/blob/2fae3a0cfea3414046f5ef6947a7c7c969714c26/stop_all.sh#L1)):*
<details><summary><i>Previously, birdy81 (Christian Vögele) wrote…</i></summary><blockquote>

Wie don't need one for windows ;-)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/inspectit-labs/spring-petclinic-microservices/3)*

**Comment by birdy81** [comment]
Review status: 2 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[start_all_with_inspectIT.sh, line 66 at r1](https://reviewable.io:443/reviews/inspectit-labs/spring-petclinic-microservices/3#-Ki4f87rswJ5h1wIqCqc:-Ki54MAnyMzMtaXKJA7C:b-896fix) ([raw file](https://github.com/inspectit-labs/spring-petclinic-microservices/blob/2fae3a0cfea3414046f5ef6947a7c7c969714c26/start_all_with_inspectIT.sh#L66)):*
<details><summary><i>Previously, birdy81 (Christian Vögele) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.

---

*[start_all_with_inspectIT.sh, line 68 at r1](https://reviewable.io:443/reviews/inspectit-labs/spring-petclinic-microservices/3#-Ki4aPzrE98VDmh8zLf2:-Ki54Nn8DhELtNbFLZUc:b-896fix) ([raw file](https://github.com/inspectit-labs/spring-petclinic-microservices/blob/2fae3a0cfea3414046f5ef6947a7c7c969714c26/start_all_with_inspectIT.sh#L68)):*
<details><summary><i>Previously, birdy81 (Christian Vögele) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.

---

*[stop_all.sh, line 1 at r1](https://reviewable.io:443/reviews/inspectit-labs/spring-petclinic-microservices/3#-Ki4aZaVO87g-clIdcvt:-Ki54P88H9wu78nc6VDs:b-896fix) ([raw file](https://github.com/inspectit-labs/spring-petclinic-microservices/blob/2fae3a0cfea3414046f5ef6947a7c7c969714c26/stop_all.sh#L1)):*
<details><summary><i>Previously, birdy81 (Christian Vögele) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/inspectit-labs/spring-petclinic-microservices/3)*

**Comment by ivansenic** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/inspectit-labs/spring-petclinic-microservices/3)*

**Review by ivansenic — APPROVED** [review]

**Pull request merged**
