### PR TITLE
Docker compose integration

### PR DESCRIPTION
**Pull request by matthias-huber**
This change is [Reviewable](https://reviewable.io/reviews/inspectit-labs/spring-petclinic-microservices/2)

### CODE REVIEW

**Comment by mariusoe** [comment]
Why are we not adding an agent in the configuration and discovery server?

And can we start the CMR before the  config server and let the config server wait for the CMR to be started (by using the wait-for-it script which is already used by the other containers (https://github.com/vishnubob/wait-for-it)). By doing this, we ensure that the CMR has been completely started before any agents are started.

---

Review status: 0 of 15 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/inspectit-labs/spring-petclinic-microservices/2#-:-KgxSG4OiYrIXcrqAZ3H:b-5dgn88)*

**Comment by mariusoe** [comment]
Review status: 0 of 15 files reviewed at latest revision, 1 unresolved discussion.

---

*[docker-compose.yml, line 10 at r2](https://reviewable.io:443/reviews/inspectit-labs/spring-petclinic-microservices/2#-KgxTQReC9nwRcrDypa7:-KgxTQReC9nwRcrDypa8:b4z06qw) ([raw file](https://github.com/inspectit-labs/spring-petclinic-microservices/blob/a37fd5db540c4c348c6455f7460c4eb918cac5d1/docker-compose.yml#L10)):*
> ```YAML
> 
>   cmr:
>     image: inspectit/cmr:latest
> ```

Can we not use the ``latest`` version but the specific one of the agents (here: 1.7.9.92). Because if we are updating the CMR image, the agent has still 1.7.9.92 but the CMR potentially a newer one.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/inspectit-labs/spring-petclinic-microservices/2)*

**Comment by matthias-huber** [comment]
As discussed we might add it later.

---

Review status: 0 of 15 files reviewed at latest revision, 1 unresolved discussion.

---

*[docker-compose.yml, line 10 at r2](https://reviewable.io:443/reviews/inspectit-labs/spring-petclinic-microservices/2#-KgxTQReC9nwRcrDypa7:-Kh97SfV4BY8T8QyTIMw:b-896fix) ([raw file](https://github.com/inspectit-labs/spring-petclinic-microservices/blob/a37fd5db540c4c348c6455f7460c4eb918cac5d1/docker-compose.yml#L10)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

Can we not use the ``latest`` version but the specific one of the agents (here: 1.7.9.92). Because if we are updating the CMR image, the agent has still 1.7.9.92 but the CMR potentially a newer one.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/inspectit-labs/spring-petclinic-microservices/2#-:-Kh6YMjTpe6CuJI-boJ3:bmw4y9z)*

**Comment by ivansenic** [comment]
Reviewed 5 of 6 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/inspectit-labs/spring-petclinic-microservices/2)*

**Comment by mariusoe** [comment]
Reviewed 5 of 6 files at r2, 2 of 2 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/inspectit-labs/spring-petclinic-microservices/2)*

**Pull request merged**
